DROP DATABASE IF EXISTS matcha;
CREATE DATABASE matcha;

\c matcha;

CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	login VARCHAR NOT NULL UNIQUE,
	name VARCHAR NOT NULL,
	first_name VARCHAR NOT NULL,
	birth DATE NOT NULL,
	sex VARCHAR,
	sex_pref VARCHAR NOT NULL DEFAULT 'B',
	mail VARCHAR NOT NULL UNIQUE,
	passwd VARCHAR NOT NULL,
	bio VARCHAR DEFAULT 'Welcome',
	latitude DECIMAL NOT NULL,
	longitude DECIMAL NOT NULL,
	ip VARCHAR NOT NULL,
	last_log TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "images" (
	"user" INT NOT NULL,
	"path" VARCHAR NOT NULL,
	"main" BOOLEAN DEFAULT FALSE,
	CONSTRAINT img_id FOREIGN KEY ("user") REFERENCES "users"("id") ON DELETE CASCADE
	) WITH (
	OIDS=FALSE
);